import "./globals.css";
// import Navbar from "@/components/shared/Navbar";
import Navbar from "../components/shared/Navbar"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-popins`}
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
