import "./globals.css";
import AuthProvider from "@/services/AuthProvider";
import TranstackProvider from "@/services/TranstackProvider";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased font-popins`}>
        <TranstackProvider>
          <AuthProvider>{children}</AuthProvider>
        </TranstackProvider>
      </body>
    </html>
  );
}
